### ISSUE TITLE
Invisible quest in inventory UI

### ISSUE THREAD

**Issue by AtzaMan** [pandapaul/minecraft-dailies-server#22]
Visible on hovering, even when disabled or abandoned.
Farming Valley modpack 0.7.6.
Bailies Dailies 6 for 1.10.2
https://drive.google.com/uc?export=view&id=0B23nTMZmrHpVSjV2MTlJX0JOTTA

**Comment by frodare** [comment]
Probably related to this: https://github.com/ToroCraft/Dailies/issues/37

**Comment by pandapaul** [comment]
Eek.  Worse than I thought.  Going to close this one though and bump priority on this issue in the mod repo:  https://github.com/ToroCraft/Dailies/issues/37

Thanks @AtzaMan for the heads up and the screenshot.  I didn't realize it was also occurring in the inventory.
